# Generated by Django 3.1.4 on 2020-12-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0002_auto_20201209_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='students',
            field=models.ManyToManyField(related_name='homeworks', through='course_api.Mark', to='course_api.Student'),
        ),
    ]
