# Generated by Django 3.1.4 on 2020-12-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0003_auto_20201209_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='lection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='course_api.lection'),
        ),
    ]
