# Generated by Django 3.1.4 on 2020-12-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0005_auto_20201209_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
